# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8642b948ed1fabb3caf6eddb68d1018aebb36adafd371bf1082a8378e03bb33c99b7f39d800e357f7fb1d0dd0a97e1c88352d11d32b0d47e031081589cc61a6

test:
  secret_key_base: dfe213d3b255fdffc424816793294ce410f487cf85b577808809c30cf0f716f68a1b9ca273e5f90a33b0352f82121cfc8e372969c50400e0cf60643d9e395d05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
